PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#>
SELECT * 
WHERE {
    GRAPH ?graph {
        ?a a qa:AnnotationOfQuestionLanguage .
        ?a oa:hasBody ?language .
    }
}
