PREFIX qa: <http://www.wdaqua.eu/qa#>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
ASK
WHERE {
    GRAPH <GRAPHID> {
        ?a a qa:AnnotationOfQuestionClassification .
        ?a oa:hasBody ?body .
        FILTER("QUESTION_CLASS" = ?body)
        ?a oa:annotatedBy ?component .
        ?a oa:annotatedAt ?time .
        ?a qa:score ?score .
    }
}
